# Generated by Django 5.0.3 on 2024-04-06 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_num", models.IntegerField(verbose_name="номер версии")),
                (
                    "version_name",
                    models.CharField(max_length=150, verbose_name="название версии"),
                ),
                (
                    "version_sign",
                    models.CharField(max_length=250, verbose_name="признак версии"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ("version_num",),
            },
        ),
    ]
